### ISSUE TITLE
pip install does not get all dependencies

### ISSUE THREAD

**Issue by py1sl** [fusion-energy/spectrum_plotter#27]
The pip install gets the openmc_tally_unit_convertor, this in turn is dependant on having openmc installed which is not retrieved.
The pip install alone does not give a working spectrum plotter

**Comment by shimwell** [comment]
Unfortunately openmc is not distributed with pypi. So it can't be included in a pip install. It can be included in a conda install if that helps. Perhaps best if I write up some install instructions and made a conda install for this package

**Comment by py1sl** [comment]
I think just a note in the install section of the readme is sufficient

**Comment by shimwell** [comment]
Thanks for reporting this, I've gone ahead and updated the readme and closed the issue, feel free to reopen if extra details are needed.

by the way the conda install for openmc now includes dagmc :tada:
